### PR TITLE
Try to split main.py into fit.py/predict.py

### PR DESCRIPTION
**Pull request by tmke8**
This was not fun.

I get an annoying error:

```
  File "fit.py", line 5, in <module>
    from main import load_json, train_classifier
  File "/home/tmk/dev/python/fair-classification/disparate_mistreatment/run_classifier/main.py", line 7, in <module>
    import funcs_disp_mist as fdm
  File "../../fair_classification/funcs_disp_mist.py", line 8, in <module>
    from cvxpy import *
  File "/home/tmk/.conda/envs/zafar/lib/python2.7/site-packages/cvxpy/__init__.py", line 18, in <module>
    from cvxpy.atoms import *
  File "/home/tmk/.conda/envs/zafar/lib/python2.7/site-packages/cvxpy/atoms/__init__.py", line 17, in <module>
    from cvxpy.atoms.affine_prod import affine_prod
  File "/home/tmk/.conda/envs/zafar/lib/python2.7/site-packages/cvxpy/atoms/affine_prod.py", line 17, in <module>
    from cvxpy.atoms.atom import Atom
  File "/home/tmk/.conda/envs/zafar/lib/python2.7/site-packages/cvxpy/atoms/atom.py", line 18, in <module>
    from .. import utilities as u
  File "/home/tmk/.conda/envs/zafar/lib/python2.7/site-packages/cvxpy/utilities/__init__.py", line 21, in <module>
    from .quadratic import QuadCoeffExtractor
  File "/home/tmk/.conda/envs/zafar/lib/python2.7/site-packages/cvxpy/utilities/quadratic.py", line 21, in <module>
    import canonInterface
  File "/home/tmk/.conda/envs/zafar/lib/python2.7/site-packages/canonInterface.py", line 16, in <module>
    import CVXcanon
  File "/home/tmk/.conda/envs/zafar/lib/python2.7/site-packages/CVXcanon.py", line 28, in <module>
    _CVXcanon = swig_import_helper()
  File "/home/tmk/.conda/envs/zafar/lib/python2.7/site-packages/CVXcanon.py", line 24, in swig_import_helper
    _mod = imp.load_module('_CVXcanon', fp, pathname, description)
ImportError: /home/tmk/.conda/envs/zafar/lib/python2.7/site-packages/_CVXcanon.so: undefined symbol: _ZSt28__throw_bad_array_new_lengthv
```

### CODE REVIEW

**Comment by tmke8** [comment]
oh no, this seems to be a deeper error: https://github.com/stan-dev/pystan/issues/294

**Comment by tmke8** [comment]
The problem seems to be that I used conda to set up the python2.7 environment for the zafar code, but conda uses a too recent version of GCC.

**Comment by olliethomas** [comment]
@tmke8 do you have any thoughts on this? Should it still be merged?

**Comment by tmke8** [comment]
Hmm, I have very little memory of this.

**Pull request closed without merging**
